import type { ServiceDTO } from "@/lib/service-types";

/** Full service seed used by scripts/seed.ts and ensureServicesSeeded() */
export const SERVICES_SEED: Omit<ServiceDTO, "_id">[] = [
  {
    title: "Garage Door Installation",
    slug: "installation",
    description:
      "Upgrade your home with a brand-new, insulated, and stylish garage door. We install R16–R18 steel doors, modern full-view glass doors, carriage style, and traditional raised panel designs.",
    content:
      "Complete professional installation including measurement, removal of the old door, hardware, weather seals, balance testing, and a safety inspection.",
    benefits: [
      "Clean, professional installation",
      "Wide selection of styles & colors",
      "Better insulation & quieter operation",
      "Honest recommendations based on your home",
    ],
    icon: "DoorClosed",
    image: "/services-installation.jpg",
    imageAlt: "New garage door installation",
    price: "Starting at $1,299",
    featured: true,
    published: true,
    order: 1,
    category: "installation",
    urgent: false,
    eyebrow: "Premium Installation Service",
    heroImage: "/services-installation.jpg",
    heroImageAlt: "Professional garage door installation in the GTA",
    includesHeading: "Our Installation Includes",
    includesDescription: "Complete, professional service from start to finish",
    includes: [
      "Free on-site measurement",
      "Removal & disposal of old door",
      "Tracks, rollers, hinges, and spring installation",
      "Weather seal & bottom rubber replacement",
      "Complete balance testing",
      "Safety inspection before finishing",
    ],
    cardsHeading: "Door Styles We Install",
    cardsDescription: "Choose from our wide selection of premium garage doors",
    cards: [
      {
        title: "R16-R18 Insulated Steel Doors",
        description:
          "Premium insulation for energy efficiency and noise reduction. Perfect for attached garages.",
        image: "/install-insulated-steel.jpg",
        imageAlt: "Insulated steel garage door",
        features: ["Energy efficient", "Noise reduction", "Durable steel construction"],
      },
      {
        title: "Modern Full-View Glass Doors",
        description:
          "Contemporary aluminum frame with tempered glass panels. Ideal for modern homes.",
        image: "/install-glass-modern.jpg",
        imageAlt: "Modern full-view glass garage door",
        features: ["Sleek modern look", "Natural light", "Aluminum frame"],
      },
      {
        title: "Carriage Style Doors",
        description:
          "Classic elegance with modern functionality. Adds curb appeal and character.",
        image: "/install-carriage.jpg",
        imageAlt: "Carriage style garage door",
        features: ["Traditional charm", "Custom designs", "High-quality materials"],
      },
      {
        title: "Traditional Raised Panel",
        description:
          "Timeless design that complements any home style. Available in various colors and finishes.",
        image: "/door-traditional.jpg",
        imageAlt: "Traditional raised panel garage door",
        features: ["Versatile style", "Color options", "Cost-effective"],
      },
    ],
    whyHeading: "Why Choose Our Installation",
    whyItems: [
      { title: "Clean, professional installation", description: "Careful workmanship from start to finish." },
      { title: "Wide selection of styles & colors", description: "Find the right look for your home." },
      { title: "Better insulation & quieter operation", description: "Premium insulated door options." },
      { title: "Honest recommendations", description: "Advice based on your home and budget." },
    ],
    ctaHeading: "Ready to Upgrade Your Garage Door?",
    ctaDescription:
      "Get a free on-site measurement and quote. Professional installation across the GTA.",
    ctaPrimary: "Request Free Quote",
    ctaPrimaryLink: "/contact",
    ctaSecondary: "Call 647-299-0283",
    ctaSecondaryLink: "tel:+16472990283",
    videoSrc: "/videos/garage-work.mp4",
    videoTitle: "Garage Door Installation Process",
    videoDescription: "See the quality of our professional installation work.",
    videoThumbnail: "/services-installation.jpg",
    phoneDisplay: "647-299-0283",
    seo: {
      title: "Garage Door Installation | Soro Garage Door Services",
      description:
        "Professional garage door installation across the GTA. Canadian-made insulated doors with free on-site estimates.",
    },
  },
  {
    title: "Garage Door Repair",
    slug: "repair",
    description:
      "Your garage door is the biggest moving part of your home — and when something breaks, you need a technician you can trust. We provide same-day repair for all issues.",
    content:
      "We repair springs, cables, tracks, rollers, hinges, panels, weatherstripping, and more — with safety as the priority.",
    benefits: [
      "Same-day service available",
      "Professional technicians",
      "Transparent pricing",
      "Fast response times",
    ],
    icon: "Wrench",
    image: "/services-repair.jpg",
    imageAlt: "Garage door repair service",
    price: "Starting at $129",
    featured: true,
    published: true,
    order: 2,
    category: "repair",
    urgent: false,
    eyebrow: "Fast, Reliable Repairs",
    heroImage: "/services-repair.jpg",
    heroImageAlt: "Garage door repair technician at work",
    includesHeading: "Common Repairs We Handle",
    includesDescription: "Safe, professional fixes for the issues homeowners face most",
    includes: [
      "Broken torsion or extension springs",
      "Snapped or frayed cables",
      "Door off-track",
      "Bent or misaligned tracks",
      "Roller & hinge damage",
      "Loud or shaking doors",
      "Damaged panels",
      "Weatherstrip replacement",
    ],
    cardsHeading: "Repair Focus Areas",
    cardsDescription: "Critical and routine repairs completed with quality parts",
    cards: [
      {
        title: "Broken Springs",
        description: "High-tension spring replacement with premium high-cycle springs.",
        image: "/repair-broken-spring.jpg",
        imageAlt: "Broken garage door spring repair",
        badge: "Critical — Same Day",
        features: ["High-cycle springs", "Safety inspection", "Balanced door"],
      },
      {
        title: "Cable Replacement",
        description: "Aircraft-grade cables installed safely — never a DIY job.",
        image: "/repair-cables.jpg",
        imageAlt: "Garage door cable replacement",
        badge: "Critical — Immediate",
        features: ["Safety first", "Quality cables", "Proper tensioning"],
      },
      {
        title: "Track Alignment",
        description: "Straighten or replace damaged track sections for smooth travel.",
        image: "/repair-tracks.jpg",
        imageAlt: "Garage door track repair",
        badge: "Urgent",
        features: ["Realignment", "Hardware check", "Quiet operation"],
      },
      {
        title: "Maintenance Tune-Up",
        description: "Lubrication, hardware check, and safety testing to prevent breakdowns.",
        image: "/services-maintenance.jpg",
        imageAlt: "Garage door maintenance",
        badge: "Preventive",
        features: ["Full inspection", "Lubrication", "Safety sensors"],
      },
    ],
    whyHeading: "Why Choose Our Repair Service",
    whyItems: [
      { title: "Same-Day Service", description: "Most repairs completed the same day you call." },
      { title: "Safety First", description: "No unsafe DIY advice for high-tension parts." },
      { title: "Quality Parts", description: "Premium springs, cables, and hardware." },
      { title: "Clear Pricing", description: "Upfront estimates before work begins." },
    ],
    ctaHeading: "Need a Garage Door Repair?",
    ctaDescription: "Call or request a free estimate. Same-day service available across the GTA.",
    ctaPrimary: "Request Free Estimate",
    ctaPrimaryLink: "/contact",
    ctaSecondary: "Call 647-299-0283",
    ctaSecondaryLink: "tel:+16472990283",
    videoSrc: "/videos/garage-work.mp4",
    videoTitle: "Professional Garage Door Repair",
    videoDescription: "See how we diagnose and fix garage door problems safely.",
    videoThumbnail: "/services-repair.jpg",
    phoneDisplay: "647-299-0283",
    seo: {
      title: "Garage Door Repair | Soro Garage Door Services",
      description:
        "Same-day garage door repair across the GTA. Springs, cables, tracks, rollers, and more.",
    },
  },
  {
    title: "Garage Door Opener Installation",
    slug: "opener",
    description:
      "We install and service top opener brands including LiftMaster, Chamberlain, Genie, and Linear — including quiet belt-drive and smart home options.",
    content:
      "Opener installation, repair, sensor alignment, WiFi setup, keypad programming, and quiet drive upgrades.",
    benefits: [
      "New opener installations",
      "Replacing noisy or broken openers",
      "Smart home integration",
      "Professional installation",
    ],
    icon: "Settings",
    image: "/services-opener.jpg",
    imageAlt: "Garage door opener installation",
    price: "Starting at $600 installed",
    featured: true,
    published: true,
    order: 3,
    category: "installation",
    urgent: false,
    eyebrow: "Smart & Quiet Openers",
    heroImage: "/services-opener.jpg",
    heroImageAlt: "Garage door opener system",
    includesHeading: "Opener Services Include",
    includesDescription: "Clean installation and reliable programming",
    includes: [
      "Belt, chain, or side-mount opener installation",
      "Safety sensor alignment",
      "WiFi & MyQ smart app setup",
      "Keypad & remote programming",
      "Removal of old opener",
      "Quiet drive system upgrades",
    ],
    cardsHeading: "Opener Options",
    cardsDescription: "Choose the right drive system for your home",
    cards: [
      {
        title: "Belt-Drive Openers",
        description: "Quiet operation ideal for homes with living space above the garage.",
        image: "/opener-technology.jpg",
        imageAlt: "Belt-drive garage door opener",
        features: ["Quiet", "Smooth travel", "Reliable"],
      },
      {
        title: "Chain-Drive Openers",
        description: "Durable and cost-effective for many residential applications.",
        image: "/services-opener.jpg",
        imageAlt: "Chain-drive garage door opener",
        features: ["Durable", "Value", "Proven"],
      },
      {
        title: "Smart / WiFi Openers",
        description: "Control and monitor your door from your phone with compatible systems.",
        image: "/opener-technology.jpg",
        imageAlt: "Smart WiFi garage door opener",
        features: ["App control", "Alerts", "MyQ ready"],
      },
      {
        title: "Opener Repair",
        description: "Sensor issues, remote failures, and motor problems diagnosed and fixed.",
        image: "/services-repair.jpg",
        imageAlt: "Garage door opener repair",
        features: ["Diagnostics", "Parts", "Safety check"],
      },
    ],
    whyHeading: "Why Choose Our Opener Service",
    whyItems: [
      { title: "Brand experience", description: "LiftMaster, Chamberlain, Genie, and more." },
      { title: "Clean install", description: "Neat mounting, wiring, and sensor setup." },
      { title: "Smart setup", description: "App and keypad programming included when needed." },
      { title: "Safety focused", description: "Sensors tested before we leave." },
    ],
    ctaHeading: "Ready for a Quieter, Smarter Opener?",
    ctaDescription: "Request a free estimate for opener installation or repair.",
    ctaPrimary: "Request Free Quote",
    ctaPrimaryLink: "/contact",
    ctaSecondary: "Call 647-299-0283",
    ctaSecondaryLink: "tel:+16472990283",
    videoSrc: "/videos/garage-work.mp4",
    videoTitle: "Opener Installation",
    videoDescription: "Professional opener installation and setup.",
    videoThumbnail: "/services-opener.jpg",
    phoneDisplay: "647-299-0283",
    seo: {
      title: "Garage Door Opener Installation | Soro Garage Door Services",
      description:
        "Garage door opener installation and repair across the GTA. Smart and quiet opener options.",
    },
  },
  {
    title: "Emergency Same-Day Garage Door Service",
    slug: "emergency",
    description:
      "A broken garage door can trap your vehicle, create a safety risk, or leave your home unsecured. Same-day emergency service available across the GTA.",
    content:
      "Emergency help for broken springs, snapped cables, stuck doors, opener failure, damaged tracks, and more.",
    benefits: [
      "Same-day availability",
      "Fully stocked service vehicle",
      "Professional, safe repair approach",
      "Fast response across the GTA",
    ],
    icon: "AlertTriangle",
    image: "/services-emergency.jpg",
    imageAlt: "Emergency garage door service",
    price: "Call for emergency pricing",
    featured: true,
    published: true,
    order: 4,
    category: "emergency",
    urgent: true,
    eyebrow: "EMERGENCY SERVICE AVAILABLE",
    heroImage: "/services-emergency.jpg",
    heroImageAlt: "Emergency garage door repair",
    includesHeading: "Emergency Issues We Handle",
    includesDescription: "Call or text for urgent help — do not attempt high-tension DIY repairs",
    includes: [
      "Broken springs",
      "Snapped cables",
      "Door stuck open or closed",
      "Opener failure",
      "Damaged tracks",
      "Vehicle trapped in the garage",
      "Safety sensor malfunction",
    ],
    cardsHeading: "When to Call Immediately",
    cardsDescription: "These situations need professional help right away",
    cards: [
      {
        title: "Door Won't Open or Close",
        description: "Stuck doors can trap vehicles and create security risks.",
        image: "/services-emergency.jpg",
        imageAlt: "Stuck garage door",
        badge: "Urgent",
        features: ["Fast diagnosis", "Same-day help", "Safe repair"],
      },
      {
        title: "Broken Spring",
        description: "High-tension springs are dangerous — call a professional.",
        image: "/repair-broken-spring.jpg",
        imageAlt: "Broken spring emergency",
        badge: "Critical",
        features: ["Do not DIY", "High-cycle springs", "Balance test"],
      },
      {
        title: "Snapped Cable",
        description: "Cables help control the door — failure can be hazardous.",
        image: "/repair-cables.jpg",
        imageAlt: "Snapped garage door cable",
        badge: "Critical",
        features: ["Aircraft-grade cables", "Safety check", "Secure install"],
      },
      {
        title: "Home Unsecured",
        description: "A door stuck open leaves your home exposed — we prioritize these calls.",
        image: "/gallery-service-truck.jpg",
        imageAlt: "Service vehicle for emergency calls",
        badge: "Priority",
        features: ["Fast response", "Stocked truck", "GTA coverage"],
      },
    ],
    whyHeading: "Why Call Soro for Emergencies",
    whyItems: [
      { title: "Same-day focus", description: "We prioritize urgent calls across the GTA." },
      { title: "Stocked vehicle", description: "Common emergency parts on hand." },
      { title: "Safety first", description: "No unsafe DIY recommendations for springs/cables." },
      { title: "Clear next steps", description: "We explain the issue and pricing before work." },
    ],
    ctaHeading: "Garage Door Stuck or Unsafe?",
    ctaDescription: "Call or text now for same-day emergency service based on availability.",
    ctaPrimary: "Call 647-299-0283",
    ctaPrimaryLink: "tel:+16472990283",
    ctaSecondary: "Text Us",
    ctaSecondaryLink: "sms:+16472990283",
    videoSrc: "/videos/garage-work.mp4",
    videoTitle: "Emergency Garage Door Service",
    videoDescription: "Fast, professional response when you need it most.",
    videoThumbnail: "/services-emergency.jpg",
    phoneDisplay: "647-299-0283",
    seo: {
      title: "Emergency Garage Door Service | Soro Garage Door Services",
      description:
        "Same-day emergency garage door repair across the GTA. Call or text 647-299-0283.",
    },
  },
  {
    title: "Commercial Garage Door Service",
    slug: "commercial",
    description:
      "Professional repair and service for commercial and industrial garage doors. We help businesses stay operating safely with fast, reliable commercial door service.",
    content:
      "Commercial springs, tracks, cables, rollers, panels, and commercial openers for warehouses, shops, and loading docks.",
    benefits: [
      "Fast response times",
      "Professional, safety-focused repairs",
      "Affordable commercial rates",
      "Experienced commercial technicians",
    ],
    icon: "Building2",
    image: "/services-commercial.jpg",
    imageAlt: "Commercial garage door service",
    price: "Starting at $150",
    featured: false,
    published: true,
    order: 5,
    category: "commercial",
    urgent: false,
    eyebrow: "Commercial & Industrial",
    heroImage: "/services-commercial.jpg",
    heroImageAlt: "Commercial overhead garage door",
    includesHeading: "Commercial Services",
    includesDescription: "Keep your facility safe and operational",
    includes: [
      "Broken torsion or high-lift springs",
      "Damaged or misaligned tracks",
      "Snapped or frayed cables",
      "Rollers, hinges, and hardware",
      "Sectional steel door panels",
      "Commercial openers (LiftMaster, Genie, Linear)",
      "Jammed or stuck overhead doors",
    ],
    cardsHeading: "Facilities We Serve",
    cardsDescription: "Reliable service for business-critical doors",
    cards: [
      {
        title: "Warehouses",
        description: "Overhead doors that keep logistics moving.",
        image: "/commercial-warehouse.jpg",
        imageAlt: "Warehouse garage door",
        features: ["High-cycle use", "Fast repairs", "Opener service"],
      },
      {
        title: "Auto Shops",
        description: "Dependable door service for busy automotive bays.",
        image: "/commercial-auto-shop.jpg",
        imageAlt: "Auto shop garage door",
        features: ["Quick turnaround", "Safety checks", "Hardware"],
      },
      {
        title: "Retail Loading Docks",
        description: "Keep receiving areas secure and operational.",
        image: "/commercial-retail.jpg",
        imageAlt: "Retail loading dock door",
        features: ["Scheduled service", "Emergency help", "Openers"],
      },
      {
        title: "Industrial Facilities",
        description: "Heavy-duty door support for industrial environments.",
        image: "/services-commercial.jpg",
        imageAlt: "Industrial garage door",
        features: ["Springs", "Tracks", "Commercial openers"],
      },
    ],
    whyHeading: "Why Businesses Choose Soro",
    whyItems: [
      { title: "Minimize downtime", description: "Fast diagnosis and practical repairs." },
      { title: "Safety focused", description: "Commercial doors done the right way." },
      { title: "Clear communication", description: "Straightforward quotes and timelines." },
      { title: "GTA coverage", description: "Serving commercial sites across the GTA." },
    ],
    ctaHeading: "Need Commercial Door Service?",
    ctaDescription: "Request a quote for repair, opener service, or urgent commercial help.",
    ctaPrimary: "Request Commercial Quote",
    ctaPrimaryLink: "/contact",
    ctaSecondary: "Call 647-299-0283",
    ctaSecondaryLink: "tel:+16472990283",
    videoSrc: "/videos/garage-work.mp4",
    videoTitle: "Commercial Door Service",
    videoDescription: "Professional commercial garage door support.",
    videoThumbnail: "/services-commercial.jpg",
    phoneDisplay: "647-299-0283",
    seo: {
      title: "Commercial Garage Door Service | Soro Garage Door Services",
      description:
        "Commercial garage door repair and service across the GTA for warehouses, shops, and loading docks.",
    },
  },
];
